
import genderdecoder


female_text = "child, quiet stuffs"
male_text = "unreasonable men"
psych = "Presentation of the study programme In the consecutive Master's programme in Clinical Psychology and Psychotherapy, existing basic knowledge is specifically deepened. In addition to the sound methodological training, the degree programme allows a high degree of specialisation and profile formation. The competences acquired in the Bachelor's programme can be expanded, especially in the field of psychotherapy. The overarching qualification goal of the Master's degree programme is to prepare students for psychotherapeutic work. The students should acquire the following competences, among others: Scientific work (incl. research planning, research methods, evaluation of empirical studies) Interpretation of research results Selection of adequate psychological diagnostic instruments as well as their application and evaluation Therapy planning and implementation of individual interventions Professional communication with patients using therapeutic conversation techniques and interventions Professional written and oral presentation as well as competences for oral patient presentation Ability to critically reflect on one's own psychotherapeutic actions and reception of feedback What you should bring with you In addition to previous knowledge of natural sciences and interest in a degree programme with a high practical component, you should also have a sound knowledge of English. Occupational fields The primary field of activity for graduates of this degree programme is psychotherapy in the outpatient and inpatient care of mental disorders. Other fields of activity include diagnostics and intervention in areas such as counselling facilities, rehabilitation facilities, prevention facilities, (occupational) health care or as an expert witness as well as an administrator in the health care sector and as a psychotherapy researcher"
print (genderdecoder.assess(female_text)) # I love how their README example alone had like three mistakes in it. 

